#!/usr/bin/env python

import sys
import smtplib
import ConfigParser

def main(jobname):

  conf = ConfigParser.ConfigParser()
  conf.read('reminder.conf')

  jobDeets = {}

  with open(jobname) as jobfile:
    line = jobfile.readline()
    while line.strip() != '':
      jobDeets[line.split(':')[0].strip().lower()] = line.split(':')[1].strip()
      line = jobfile.readline()
    
    jobmessage = "From: {} <{}>\n".format(conf.get(jobDeets['from'], 'name'), conf.get(jobDeets['from'], 'address'))
    jobmessage += "To: {}\n".format(jobDeets['to'])
    jobmessage += "Subject: {}\n\n".format(jobDeets['subject'])
    jobmessage += jobfile.read()

  smtpHost = conf.get(jobDeets['from'], 'host')
  smtpUser = conf.get(jobDeets['from'], 'user')
  smtpPass = conf.get(jobDeets['from'], 'pass')
  fromAddr = conf.get(jobDeets['from'], 'address')

  smtp = smtplib.SMTP_SSL(smtpHost)
  smtp.login(smtpUser, smtpPass)
  smtp.sendmail(fromAddr, jobDeets['to'], jobmessage)

if __name__ == "__main__":
  main(sys.argv[1])
